
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://demo.webservices.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWebService {


    /**
     * 
     * @param guestname
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String sayHello(
        @WebParam(name = "guestname", partName = "guestname")
        String guestname);

}
